[package]
name = "rendy-init"
version = "0.3.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-frame"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's easy initialization tool"

[features]
empty = ["rendy-core/empty"]
dx12 = ["rendy-core/dx12"]
gl = ["rendy-core/gl"]
metal = ["rendy-core/metal"]
vulkan = ["rendy-core/vulkan"]
no-slow-safety-checks = ["rendy-core/no-slow-safety-checks"]
wsi-winit = ["rendy-core/winit"]

[dependencies]
rendy-command = { version = "0.3.0", path = "../command" }
rendy-factory = { version = "0.3.1", path = "../factory" }
rendy-core = { version = "0.3.1", path = "../core" }
rendy-wsi = { version = "0.3.0", path = "../wsi" }

failure = "0.1"
log = "0.4"
