[workspace]

members = [
    "command",
    "descriptor",
    "factory",
    "frame",
    "memory",
    "mesh",
    "rendy",
    "resource",
    "shader",
    "wsi",
    "chain",
    "graph",
    "util",
    "texture",
    "examples",
]

[profile.release]
lto = true
