[package]
name = "rendy-examples"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
keywords = ["graphics", "gfx-hal", "rendy"]
description = "Higher-level graphics abstrations based on gfx-hal"
categories = ["rendering"]
readme = "../README.md"
exclude = ["www/generated"]

[dependencies]
cfg-if = "*"
env_logger = "0.6"
failure = "0.1"
genmesh = "0.6"
lazy_static = "1.0"
log = "0.4"
nalgebra = "0.18"
palette = "0.4"
rand = "0.6"
rendy = { path = "../rendy", version = "0.3.1", features = ["base", "empty"], default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "0.1"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["XmlHttpRequest"] }
js-sys = "0.3"

[features]
dx12 = ["rendy/dx12"]
gl = ["rendy/gl"]
metal = ["rendy/metal"]
vulkan = ["rendy/vulkan"]
wsi-winit = ["rendy/wsi-winit"]
shader-compiler = ["rendy/shader-compiler"]
texture-image = ["rendy/texture-image"]
mesh = ["rendy/mesh"]

[[bin]]
name = "triangle"
path = "src/triangle/main.rs"

[[bin]]
name = "sprite"
path = "src/sprite/main.rs"
required-features = ["texture-image"]

[[bin]]
name = "meshes"
path = "src/meshes/main.rs"
required-features = ["mesh"]

[[bin]]
name = "quads"
path = "src/quads/main.rs"
